name: PluginUtilities
main: com.cosimo.utilities.UtilitiesPlugin
version: 1.0.0
api-version: 1.20
author: CosimoTiger
description: PluginUtilities is a code utility library for Spigot developers.
website: https://github.com/CosimoTiger/plugin-utilities