name: PluginUtilities
main: memecat.fatcat.utilities.UtilitiesPlugin
version: 1.1.0
api-version: 1.16
author: FatCatBuilds
description: PluginUtilities is a code utility library for Spigot developers.
website: https://github.com/memecatFatCat/plugin-utilities